### PR TITLE
Add Makefiles for building into a library

### PR DESCRIPTION
**Pull request by fxfactorial**
Thanks for this library. I ended up making these for myself and figured it would make things easier for other people as well.

### CODE REVIEW

**Comment by fxfactorial** [comment]
@chrishulbert Does no one care about this project anymore? Lots of other seemingly good PRs available as well.

**Comment by chrishulbert** [comment]
Hi! Not sure why you're messaging me? I'm not involved in this project
(haven't been for years).

**Comment by fxfactorial** [comment]
@chrishulbert Sorry, your handle was the last to have a commit so I assumed you were involved.

**Comment by chrishulbert** [comment]
Understandable then! I'm not sure who is the admin now.

**Comment by fxfactorial** [comment]
seems no one cares about this

**Pull request closed without merging**
